mode: development

http:
  host: 'localhost'
  port: 8080

db:
  mysql:
    host: 'xxx.xx.xxx.x'
    port: 3306
    username: 'root'
    password: 'care'
    database: 'cell'

  mongoose: 'mongodb://care:care@115.29.243.9/cell'
