# 模式
mode: development

# 服务启动地址
http:
  host: localhost
  port: 3000

# 数据库
db:
  mysql:
    host: xxx.xx.xxx.x
    port: 3306
    username: xxxx
    password: xxxx
    database: xxxx

  mongoose: mongodb://care:care@xxx.xx.xxx.x/xxxx
