# 模式
mode: uat

# 服务启动地址
http:
  host: localhost
  port: 3000

# 数据库
db:
  mysql:
    host: 115.29.243.9
    port: 3306
    username: root
    password: care
    database: cellink

  mongoose: mongodb://care:care@115.29.243.9/cell

  redis: redis://xxx.xxx.xxx.xxx:6379
