# 模式
mode: development

# 服务启动地址
http:
  host: localhost
  port: 8080

# 数据库
db:
  mysql:
    host: 114.115.208.175
    port: 3306
    username: root
    password: yunfuwuxiaoguanjia
    database: cellink

  mongoose: mongodb+srv://root:root@celllink.8zznxkj.mongodb.net/celllink

  redis: redis://114.115.208.175:6379
